config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    #root "users#new"
    root "sessions#new"
    resources :articles
    get 'signup', to: 'users#new'
    resources :users, except: [:new] 
    get 'session/login', to: 'sessions#login'
    post 'session/login',to:  'sessions#signin'
    delete '/logout', to: 'sessions#destory'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
	has_secure_password
	validates :username, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
      !!current_user
  end

  def require_user
   if !logged_in?
    redirect_to root_path
   end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		#@articles = Article.all
		
		@articles = current_user.articles
        
	end

	def new 
		@article = Article.new
	end

	def create 
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
            redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])

	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
        redirect_to article_path(@article)
    else
        render 'edit'
    end
  end


    def destroy
       @article = Article.find(params[:id])
       @article.destroy
       redirect_to articles_path
    end


	private
	  def article_params
	  	params.require(:article).permit(:title,:description)
	  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
     
      
    
  end

  def destory
    sessions[:user_id] = nil
    redirect_to root_path
  end

  def login
    
  end
   def signin
    user = User.find_by(username: params[:username])  #&& User.find_by(password: params[:password]) 
    if user  && user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to articles_path
       #redirect_to 'user/show'

    else
      redirect_to root_path
    end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
      @users = User.all
      #@users = current_arctiles.user
    end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to articles_path
			#redirect_to users_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
         @user = User.find(params[:id])
         if @user.update(user_params)
            redirect_to articles_path
         else
            render 'edit'
         end
    end

    def show
       @user = User.find(params[:id])
    end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= link_to 'Back', articles_path %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/articles/index.html.erb
<h1> Listing all Articles </h1>
<p>
<%= link_to "Create new article", new_article_path %>
</p>
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.description %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%=link_to 'Delete', article_path(article), data: {turbo_method: :delete,} %></td>
        
	</tr>

	<% end %>
</table>

app/views/articles/new.html.erb
<h1> Create an Article </h1>

<%= form_for @article do |f| %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.submit %>
</p>
<%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/show.html.erb
<h1> Showing Selected Article </h1>

<p>
	Title: <%= @article.title %>
</p>

<p>
	Description: <%= @article.description %>
</p>
<%= link_to 'Back', articles_path %>

<%= link_to "Edit", edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1> Edit user Account </h1>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :email %><br>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<%= link_to 'Cancel request and Return to Articles Listing', articles_path %>
<% end %>

app/views/users/index.html.erb
<h2> New Article </h2>
<%# link_to "Create new article", new_article_path %><br>
<%= @users.each do |user| %>
    <%= link_to user.username, user_path(user) %>
    <%= link_to @article.user.username, user_path(@article.user) %>

    
<% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>


<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :email %><br>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<%= link_to 'Cancel request and Return to Articles Listing', articles_path %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome to Blog <%= @user.username %> </h1>